USE [master]
GO
/****** Object:  Database [TreeDB]    Script Date: 18-05-2022 18:54:12 ******/
CREATE DATABASE [TreeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TreeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TreeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TreeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TreeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TreeDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TreeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TreeDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TreeDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TreeDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TreeDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TreeDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TreeDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TreeDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TreeDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TreeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TreeDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TreeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TreeDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TreeDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TreeDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TreeDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TreeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TreeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TreeDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TreeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TreeDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TreeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TreeDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TreeDB] SET RECOVERY FULL 
GO
ALTER DATABASE [TreeDB] SET  MULTI_USER 
GO
ALTER DATABASE [TreeDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TreeDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TreeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TreeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TreeDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TreeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TreeDB', N'ON'
GO
ALTER DATABASE [TreeDB] SET QUERY_STORE = OFF
GO
USE [TreeDB]
GO
/****** Object:  Table [dbo].[datalogger]    Script Date: 18-05-2022 18:54:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[datalogger](
	[datalogger_id] [int] IDENTITY(1,1) NOT NULL,
	[plant_id] [int] NULL,
 CONSTRAINT [PK_datalogger] PRIMARY KEY CLUSTERED 
(
	[datalogger_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[measurement]    Script Date: 18-05-2022 18:54:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[measurement](
	[measurement_id] [int] IDENTITY(1,1) NOT NULL,
	[plant_id] [int] NULL,
	[soil_humidity] [real] NULL,
	[air_humidity] [real] NULL,
	[air_temerature] [real] NULL,
 CONSTRAINT [PK_measurement] PRIMARY KEY CLUSTERED 
(
	[measurement_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[plant]    Script Date: 18-05-2022 18:54:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[plant](
	[plant_id] [int] IDENTITY(1,1) NOT NULL,
	[plant_type_id] [int] NULL,
	[warranty_start_date] [date] NULL,
	[price] [real] NULL,
 CONSTRAINT [PK_plant] PRIMARY KEY CLUSTERED 
(
	[plant_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[plant_type]    Script Date: 18-05-2022 18:54:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[plant_type](
	[plant_type_id] [int] IDENTITY(1,1) NOT NULL,
	[plant_type_name] [nchar](256) NULL,
 CONSTRAINT [PK_plant_type] PRIMARY KEY CLUSTERED 
(
	[plant_type_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[datalogger]  WITH CHECK ADD  CONSTRAINT [FK_datalogger_plant] FOREIGN KEY([plant_id])
REFERENCES [dbo].[plant] ([plant_id])
GO
ALTER TABLE [dbo].[datalogger] CHECK CONSTRAINT [FK_datalogger_plant]
GO
ALTER TABLE [dbo].[measurement]  WITH CHECK ADD  CONSTRAINT [FK_measurement_plant] FOREIGN KEY([plant_id])
REFERENCES [dbo].[plant] ([plant_id])
GO
ALTER TABLE [dbo].[measurement] CHECK CONSTRAINT [FK_measurement_plant]
GO
ALTER TABLE [dbo].[plant]  WITH CHECK ADD  CONSTRAINT [FK_plant_plant_type] FOREIGN KEY([plant_type_id])
REFERENCES [dbo].[plant_type] ([plant_type_id])
GO
ALTER TABLE [dbo].[plant] CHECK CONSTRAINT [FK_plant_plant_type]
GO
USE [master]
GO
ALTER DATABASE [TreeDB] SET  READ_WRITE 
GO

use [TreeDB]
INSERT INTO plant_type (plant_type_name)  VALUES ('big tree');
INSERT INTO plant_type (plant_type_name)  VALUES ('small tree');

insert into plant (plant_type_id,warranty_start_date,price) values (1,NULL,33.33);

insert into datalogger (plant_id) values (1);

insert into measurement (plant_id,soil_humidity,air_humidity,air_temerature) values (1,22.22,33.33,44.44);
insert into measurement (plant_id,soil_humidity,air_humidity,air_temerature) values (1,41.41,21.21,31.31);